-- Enable required extensions
CREATE EXTENSION IF NOT EXISTS citext;
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS pg_trgm;
--> statement-breakpoint
CREATE TABLE "agent_events" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "agent_events_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"tenant_id" bigint NOT NULL,
	"agent_run_id" bigint NOT NULL,
	"ts" timestamp with time zone DEFAULT now() NOT NULL,
	"type" text NOT NULL,
	"payload_json" jsonb NOT NULL
);
--> statement-breakpoint
CREATE TABLE "agent_runs" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "agent_runs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"tenant_id" bigint NOT NULL,
	"project_id" bigint NOT NULL,
	"ticket_id" bigint,
	"provider" text NOT NULL,
	"mode" text NOT NULL,
	"status" text NOT NULL,
	"input_prompt" text NOT NULL,
	"output_summary" text,
	"artifacts_json" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"cost_cents" bigint DEFAULT 0 NOT NULL,
	"started_at" timestamp with time zone,
	"ended_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "code_diffs" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "code_diffs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"tenant_id" bigint NOT NULL,
	"agent_run_id" bigint,
	"repository_id" bigint NOT NULL,
	"base_ref" text NOT NULL,
	"head_ref" text NOT NULL,
	"unified_diff" text NOT NULL,
	"summary" text,
	"stats_json" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "audit_log" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "audit_log_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"tenant_id" bigint NOT NULL,
	"actor_user_id" bigint,
	"action" text NOT NULL,
	"target_type" text NOT NULL,
	"target_id" bigint NOT NULL,
	"payload_json" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"ts" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "project_budgets" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "project_budgets_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"tenant_id" bigint NOT NULL,
	"project_id" bigint NOT NULL,
	"period" text NOT NULL,
	"limit_cents" bigint NOT NULL,
	"soft_limit_cents" bigint,
	"currency" text DEFAULT 'USD' NOT NULL,
	"enforce_hard_stop" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "connectors" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "connectors_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"tenant_id" bigint NOT NULL,
	"provider" smallint NOT NULL,
	"external_org" text,
	"auth_type" smallint NOT NULL,
	"access_token_enc" "bytea" NOT NULL,
	"refresh_token_enc" "bytea",
	"scopes_json" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"status" smallint DEFAULT 1 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"revoked_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "repositories" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "repositories_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"tenant_id" bigint NOT NULL,
	"connector_id" bigint NOT NULL,
	"provider" smallint NOT NULL,
	"external_repo_id" bigint,
	"owner" text NOT NULL,
	"name" text NOT NULL,
	"full_name" text NOT NULL,
	"clone_url" text NOT NULL,
	"default_branch" text NOT NULL,
	"is_enabled" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "webhooks" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "webhooks_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"tenant_id" bigint NOT NULL,
	"connector_id" bigint NOT NULL,
	"provider" smallint NOT NULL,
	"external_webhook_id" bigint,
	"secret_enc" "bytea" NOT NULL,
	"events_json" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"target_path" text NOT NULL,
	"status" smallint DEFAULT 1 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "feature_aliases" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "feature_aliases_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"tenant_id" bigint NOT NULL,
	"feature_id" bigint NOT NULL,
	"alias" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "feature_repository_map" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "feature_repository_map_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"tenant_id" bigint NOT NULL,
	"feature_id" bigint NOT NULL,
	"repository_id" bigint NOT NULL,
	"change_type" smallint NOT NULL,
	"priority" smallint DEFAULT 2 NOT NULL,
	"notes" text
);
--> statement-breakpoint
CREATE TABLE "features" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "features_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"tenant_id" bigint NOT NULL,
	"project_id" bigint NOT NULL,
	"key" text NOT NULL,
	"name" text NOT NULL,
	"description" text,
	"tags" text[] DEFAULT '{}'::text[] NOT NULL,
	"owner_team" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "hooks" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "hooks_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"tenant_id" bigint NOT NULL,
	"name" text NOT NULL,
	"event_type" text NOT NULL,
	"runtime" smallint DEFAULT 1 NOT NULL,
	"code" text NOT NULL,
	"enabled" boolean DEFAULT true NOT NULL,
	"timeout_ms" integer DEFAULT 5000 NOT NULL,
	"created_by" bigint,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "tenants" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tenants_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"slug" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "tenants_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "roles" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "roles_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"tenant_id" bigint NOT NULL,
	"name" text NOT NULL,
	"permissions_json" jsonb DEFAULT '{}'::jsonb NOT NULL
);
--> statement-breakpoint
CREATE TABLE "user_roles" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "user_roles_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"tenant_id" bigint NOT NULL,
	"user_id" bigint NOT NULL,
	"role_id" bigint NOT NULL
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "users_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"tenant_id" bigint NOT NULL,
	"email" text NOT NULL,
	"name" text,
	"github_user_id" bigint,
	"status" smallint DEFAULT 1 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "boards" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "boards_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"tenant_id" bigint NOT NULL,
	"project_id" bigint NOT NULL,
	"name" text NOT NULL,
	"columns_json" jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "projects" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "projects_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"tenant_id" bigint NOT NULL,
	"name" text NOT NULL,
	"key" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "tickets" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tickets_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"tenant_id" bigint NOT NULL,
	"project_id" bigint NOT NULL,
	"board_id" bigint NOT NULL,
	"column_key" text NOT NULL,
	"title" text NOT NULL,
	"description_md" text,
	"priority" smallint DEFAULT 2,
	"labels_json" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"assignee_user_id" bigint,
	"repository_id" bigint,
	"branch" text,
	"pr_url" text,
	"status_meta_json" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_by" bigint,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "project_repositories" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "project_repositories_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"tenant_id" bigint NOT NULL,
	"project_id" bigint NOT NULL,
	"repository_id" bigint NOT NULL,
	"repo_role" smallint NOT NULL,
	"is_primary" boolean DEFAULT false NOT NULL,
	"notes" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "repository_aliases" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "repository_aliases_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"tenant_id" bigint NOT NULL,
	"repository_id" bigint NOT NULL,
	"alias" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "custom_instructions" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "custom_instructions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"tenant_id" bigint NOT NULL,
	"scope_type" text NOT NULL,
	"scope_id" bigint NOT NULL,
	"mode" text NOT NULL,
	"content_md" text NOT NULL,
	"priority" integer DEFAULT 100 NOT NULL,
	"enabled" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "default_agent_instructions" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "default_agent_instructions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"tenant_id" bigint NOT NULL,
	"provider" text NOT NULL,
	"content_md" text NOT NULL,
	"enabled" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "default_agent_tools" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "default_agent_tools_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"tenant_id" bigint NOT NULL,
	"provider" text NOT NULL,
	"allowed_tools_json" jsonb NOT NULL,
	"enabled" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "build_pipelines" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "build_pipelines_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"tenant_id" bigint NOT NULL,
	"project_id" bigint NOT NULL,
	"repository_id" bigint NOT NULL,
	"provider" smallint NOT NULL,
	"name" text NOT NULL,
	"config_json" jsonb NOT NULL,
	"enabled" boolean DEFAULT true NOT NULL,
	"pipeline_repository_id" bigint,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "deployment_steps" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "deployment_steps_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"tenant_id" bigint NOT NULL,
	"deployment_id" bigint NOT NULL,
	"step_order" integer NOT NULL,
	"kind" smallint NOT NULL,
	"pipeline_id" bigint,
	"repository_id" bigint,
	"config_json" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"status" smallint DEFAULT 1 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "deployment_targets" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "deployment_targets_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"tenant_id" bigint NOT NULL,
	"project_id" bigint NOT NULL,
	"name" text NOT NULL,
	"provider" text NOT NULL,
	"config_json" jsonb NOT NULL,
	"enabled" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "deployments" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "deployments_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"tenant_id" bigint NOT NULL,
	"project_id" bigint NOT NULL,
	"ticket_id" bigint,
	"deployment_target_id" bigint NOT NULL,
	"status" smallint DEFAULT 1 NOT NULL,
	"created_by" bigint,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"started_at" timestamp with time zone,
	"ended_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "pipeline_runs" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pipeline_runs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"tenant_id" bigint NOT NULL,
	"pipeline_id" bigint NOT NULL,
	"external_run_id" bigint,
	"status" text NOT NULL,
	"conclusion" text,
	"url" text,
	"started_at" timestamp with time zone,
	"completed_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "api_keys" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "api_keys_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"tenant_id" bigint NOT NULL,
	"user_id" bigint,
	"name" text NOT NULL,
	"prefix" text NOT NULL,
	"key_hash" "bytea" NOT NULL,
	"scopes_json" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"status" smallint DEFAULT 1 NOT NULL,
	"last_used_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"revoked_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "env_var_sets" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "env_var_sets_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"tenant_id" bigint NOT NULL,
	"scope_type" text NOT NULL,
	"scope_id" bigint NOT NULL,
	"name" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "env_vars" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "env_vars_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"tenant_id" bigint NOT NULL,
	"set_id" bigint NOT NULL,
	"key" text NOT NULL,
	"value_enc" "bytea" NOT NULL,
	"is_secret" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "agent_events" ADD CONSTRAINT "agent_events_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "agent_events" ADD CONSTRAINT "agent_events_agent_run_id_agent_runs_id_fk" FOREIGN KEY ("agent_run_id") REFERENCES "public"."agent_runs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "agent_runs" ADD CONSTRAINT "agent_runs_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "agent_runs" ADD CONSTRAINT "agent_runs_project_id_projects_id_fk" FOREIGN KEY ("project_id") REFERENCES "public"."projects"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "agent_runs" ADD CONSTRAINT "agent_runs_ticket_id_tickets_id_fk" FOREIGN KEY ("ticket_id") REFERENCES "public"."tickets"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "code_diffs" ADD CONSTRAINT "code_diffs_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "code_diffs" ADD CONSTRAINT "code_diffs_agent_run_id_agent_runs_id_fk" FOREIGN KEY ("agent_run_id") REFERENCES "public"."agent_runs"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "code_diffs" ADD CONSTRAINT "code_diffs_repository_id_repositories_id_fk" FOREIGN KEY ("repository_id") REFERENCES "public"."repositories"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "audit_log" ADD CONSTRAINT "audit_log_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "audit_log" ADD CONSTRAINT "audit_log_actor_user_id_users_id_fk" FOREIGN KEY ("actor_user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "project_budgets" ADD CONSTRAINT "project_budgets_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "project_budgets" ADD CONSTRAINT "project_budgets_project_id_projects_id_fk" FOREIGN KEY ("project_id") REFERENCES "public"."projects"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "connectors" ADD CONSTRAINT "connectors_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "repositories" ADD CONSTRAINT "repositories_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "repositories" ADD CONSTRAINT "repositories_connector_id_connectors_id_fk" FOREIGN KEY ("connector_id") REFERENCES "public"."connectors"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "webhooks" ADD CONSTRAINT "webhooks_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "webhooks" ADD CONSTRAINT "webhooks_connector_id_connectors_id_fk" FOREIGN KEY ("connector_id") REFERENCES "public"."connectors"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "feature_aliases" ADD CONSTRAINT "feature_aliases_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "feature_aliases" ADD CONSTRAINT "feature_aliases_feature_id_features_id_fk" FOREIGN KEY ("feature_id") REFERENCES "public"."features"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "feature_repository_map" ADD CONSTRAINT "feature_repository_map_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "feature_repository_map" ADD CONSTRAINT "feature_repository_map_feature_id_features_id_fk" FOREIGN KEY ("feature_id") REFERENCES "public"."features"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "feature_repository_map" ADD CONSTRAINT "feature_repository_map_repository_id_repositories_id_fk" FOREIGN KEY ("repository_id") REFERENCES "public"."repositories"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "features" ADD CONSTRAINT "features_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "features" ADD CONSTRAINT "features_project_id_projects_id_fk" FOREIGN KEY ("project_id") REFERENCES "public"."projects"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "hooks" ADD CONSTRAINT "hooks_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "hooks" ADD CONSTRAINT "hooks_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "roles" ADD CONSTRAINT "roles_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_roles" ADD CONSTRAINT "user_roles_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_roles" ADD CONSTRAINT "user_roles_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_roles" ADD CONSTRAINT "user_roles_role_id_roles_id_fk" FOREIGN KEY ("role_id") REFERENCES "public"."roles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "users" ADD CONSTRAINT "users_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "boards" ADD CONSTRAINT "boards_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "boards" ADD CONSTRAINT "boards_project_id_projects_id_fk" FOREIGN KEY ("project_id") REFERENCES "public"."projects"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "projects" ADD CONSTRAINT "projects_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tickets" ADD CONSTRAINT "tickets_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tickets" ADD CONSTRAINT "tickets_project_id_projects_id_fk" FOREIGN KEY ("project_id") REFERENCES "public"."projects"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tickets" ADD CONSTRAINT "tickets_board_id_boards_id_fk" FOREIGN KEY ("board_id") REFERENCES "public"."boards"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tickets" ADD CONSTRAINT "tickets_assignee_user_id_users_id_fk" FOREIGN KEY ("assignee_user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tickets" ADD CONSTRAINT "tickets_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "project_repositories" ADD CONSTRAINT "project_repositories_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "project_repositories" ADD CONSTRAINT "project_repositories_project_id_projects_id_fk" FOREIGN KEY ("project_id") REFERENCES "public"."projects"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "project_repositories" ADD CONSTRAINT "project_repositories_repository_id_repositories_id_fk" FOREIGN KEY ("repository_id") REFERENCES "public"."repositories"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "repository_aliases" ADD CONSTRAINT "repository_aliases_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "repository_aliases" ADD CONSTRAINT "repository_aliases_repository_id_repositories_id_fk" FOREIGN KEY ("repository_id") REFERENCES "public"."repositories"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "custom_instructions" ADD CONSTRAINT "custom_instructions_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "default_agent_instructions" ADD CONSTRAINT "default_agent_instructions_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "default_agent_tools" ADD CONSTRAINT "default_agent_tools_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "build_pipelines" ADD CONSTRAINT "build_pipelines_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "build_pipelines" ADD CONSTRAINT "build_pipelines_project_id_projects_id_fk" FOREIGN KEY ("project_id") REFERENCES "public"."projects"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "build_pipelines" ADD CONSTRAINT "build_pipelines_repository_id_repositories_id_fk" FOREIGN KEY ("repository_id") REFERENCES "public"."repositories"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "build_pipelines" ADD CONSTRAINT "build_pipelines_pipeline_repository_id_repositories_id_fk" FOREIGN KEY ("pipeline_repository_id") REFERENCES "public"."repositories"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "deployment_steps" ADD CONSTRAINT "deployment_steps_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "deployment_steps" ADD CONSTRAINT "deployment_steps_deployment_id_deployments_id_fk" FOREIGN KEY ("deployment_id") REFERENCES "public"."deployments"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "deployment_steps" ADD CONSTRAINT "deployment_steps_pipeline_id_build_pipelines_id_fk" FOREIGN KEY ("pipeline_id") REFERENCES "public"."build_pipelines"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "deployment_steps" ADD CONSTRAINT "deployment_steps_repository_id_repositories_id_fk" FOREIGN KEY ("repository_id") REFERENCES "public"."repositories"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "deployment_targets" ADD CONSTRAINT "deployment_targets_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "deployment_targets" ADD CONSTRAINT "deployment_targets_project_id_projects_id_fk" FOREIGN KEY ("project_id") REFERENCES "public"."projects"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "deployments" ADD CONSTRAINT "deployments_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "deployments" ADD CONSTRAINT "deployments_project_id_projects_id_fk" FOREIGN KEY ("project_id") REFERENCES "public"."projects"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "deployments" ADD CONSTRAINT "deployments_ticket_id_tickets_id_fk" FOREIGN KEY ("ticket_id") REFERENCES "public"."tickets"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "deployments" ADD CONSTRAINT "deployments_deployment_target_id_deployment_targets_id_fk" FOREIGN KEY ("deployment_target_id") REFERENCES "public"."deployment_targets"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "deployments" ADD CONSTRAINT "deployments_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pipeline_runs" ADD CONSTRAINT "pipeline_runs_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pipeline_runs" ADD CONSTRAINT "pipeline_runs_pipeline_id_build_pipelines_id_fk" FOREIGN KEY ("pipeline_id") REFERENCES "public"."build_pipelines"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "api_keys" ADD CONSTRAINT "api_keys_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "api_keys" ADD CONSTRAINT "api_keys_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "env_var_sets" ADD CONSTRAINT "env_var_sets_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "env_vars" ADD CONSTRAINT "env_vars_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "env_vars" ADD CONSTRAINT "env_vars_set_id_env_var_sets_id_fk" FOREIGN KEY ("set_id") REFERENCES "public"."env_var_sets"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "agent_events_tenant_run_ts_idx" ON "agent_events" USING btree ("tenant_id","agent_run_id","ts");--> statement-breakpoint
CREATE INDEX "agent_runs_tenant_project_created_idx" ON "agent_runs" USING btree ("tenant_id","project_id","created_at");--> statement-breakpoint
CREATE INDEX "agent_runs_tenant_status_idx" ON "agent_runs" USING btree ("tenant_id","status");--> statement-breakpoint
CREATE INDEX "agent_runs_tenant_provider_mode_idx" ON "agent_runs" USING btree ("tenant_id","provider","mode");--> statement-breakpoint
CREATE INDEX "code_diffs_tenant_repo_created_idx" ON "code_diffs" USING btree ("tenant_id","repository_id","created_at");--> statement-breakpoint
CREATE INDEX "code_diffs_tenant_run_idx" ON "code_diffs" USING btree ("tenant_id","agent_run_id");--> statement-breakpoint
CREATE INDEX "audit_log_tenant_ts_idx" ON "audit_log" USING btree ("tenant_id","ts");--> statement-breakpoint
CREATE INDEX "audit_log_tenant_actor_ts_idx" ON "audit_log" USING btree ("tenant_id","actor_user_id","ts");--> statement-breakpoint
CREATE UNIQUE INDEX "project_budgets_tenant_project_period_uniq" ON "project_budgets" USING btree ("tenant_id","project_id","period");--> statement-breakpoint
CREATE INDEX "project_budgets_tenant_project_idx" ON "project_budgets" USING btree ("tenant_id","project_id");--> statement-breakpoint
CREATE INDEX "connectors_tenant_provider_status_idx" ON "connectors" USING btree ("tenant_id","provider","status");--> statement-breakpoint
CREATE INDEX "connectors_tenant_created_idx" ON "connectors" USING btree ("tenant_id","created_at");--> statement-breakpoint
CREATE UNIQUE INDEX "repos_tenant_provider_fullname_uniq" ON "repositories" USING btree ("tenant_id","provider","full_name");--> statement-breakpoint
CREATE INDEX "repos_tenant_connector_idx" ON "repositories" USING btree ("tenant_id","connector_id");--> statement-breakpoint
CREATE INDEX "repos_tenant_enabled_idx" ON "repositories" USING btree ("tenant_id","is_enabled");--> statement-breakpoint
CREATE INDEX "repos_tenant_external_idx" ON "repositories" USING btree ("tenant_id","external_repo_id");--> statement-breakpoint
CREATE INDEX "webhooks_tenant_connector_status_idx" ON "webhooks" USING btree ("tenant_id","connector_id","status");--> statement-breakpoint
CREATE UNIQUE INDEX "feat_aliases_tenant_feat_alias_uniq" ON "feature_aliases" USING btree ("tenant_id","feature_id","alias");--> statement-breakpoint
CREATE UNIQUE INDEX "feat_repo_map_tenant_feat_repo_uniq" ON "feature_repository_map" USING btree ("tenant_id","feature_id","repository_id");--> statement-breakpoint
CREATE INDEX "feat_repo_map_tenant_feat_priority_idx" ON "feature_repository_map" USING btree ("tenant_id","feature_id","priority");--> statement-breakpoint
CREATE INDEX "feat_repo_map_tenant_repo_idx" ON "feature_repository_map" USING btree ("tenant_id","repository_id");--> statement-breakpoint
CREATE UNIQUE INDEX "features_tenant_project_key_uniq" ON "features" USING btree ("tenant_id","project_id","key");--> statement-breakpoint
CREATE INDEX "hooks_tenant_event_enabled_idx" ON "hooks" USING btree ("tenant_id","event_type","enabled");--> statement-breakpoint
CREATE UNIQUE INDEX "roles_tenant_name_uniq" ON "roles" USING btree ("tenant_id","name");--> statement-breakpoint
CREATE UNIQUE INDEX "user_roles_tenant_user_role_uniq" ON "user_roles" USING btree ("tenant_id","user_id","role_id");--> statement-breakpoint
CREATE INDEX "user_roles_tenant_user_idx" ON "user_roles" USING btree ("tenant_id","user_id");--> statement-breakpoint
CREATE UNIQUE INDEX "users_tenant_email_uniq" ON "users" USING btree ("tenant_id","email");--> statement-breakpoint
CREATE INDEX "users_tenant_status_idx" ON "users" USING btree ("tenant_id","status");--> statement-breakpoint
CREATE INDEX "users_tenant_github_idx" ON "users" USING btree ("tenant_id","github_user_id");--> statement-breakpoint
CREATE UNIQUE INDEX "boards_tenant_project_name_uniq" ON "boards" USING btree ("tenant_id","project_id","name");--> statement-breakpoint
CREATE INDEX "boards_tenant_project_idx" ON "boards" USING btree ("tenant_id","project_id");--> statement-breakpoint
CREATE UNIQUE INDEX "projects_tenant_key_uniq" ON "projects" USING btree ("tenant_id","key");--> statement-breakpoint
CREATE INDEX "projects_tenant_created_idx" ON "projects" USING btree ("tenant_id","created_at");--> statement-breakpoint
CREATE INDEX "tickets_tenant_project_col_idx" ON "tickets" USING btree ("tenant_id","project_id","column_key");--> statement-breakpoint
CREATE INDEX "tickets_tenant_assignee_idx" ON "tickets" USING btree ("tenant_id","assignee_user_id");--> statement-breakpoint
CREATE INDEX "tickets_tenant_repo_idx" ON "tickets" USING btree ("tenant_id","repository_id");--> statement-breakpoint
CREATE INDEX "tickets_tenant_updated_idx" ON "tickets" USING btree ("tenant_id","updated_at");--> statement-breakpoint
CREATE UNIQUE INDEX "project_repos_tenant_project_repo_uniq" ON "project_repositories" USING btree ("tenant_id","project_id","repository_id");--> statement-breakpoint
CREATE INDEX "project_repos_tenant_project_role_idx" ON "project_repositories" USING btree ("tenant_id","project_id","repo_role");--> statement-breakpoint
CREATE INDEX "project_repos_tenant_repo_idx" ON "project_repositories" USING btree ("tenant_id","repository_id");--> statement-breakpoint
CREATE UNIQUE INDEX "repo_aliases_tenant_repo_alias_uniq" ON "repository_aliases" USING btree ("tenant_id","repository_id","alias");--> statement-breakpoint
CREATE UNIQUE INDEX "custom_instr_tenant_scope_mode_priority_uniq" ON "custom_instructions" USING btree ("tenant_id","scope_type","scope_id","mode","priority");--> statement-breakpoint
CREATE INDEX "custom_instr_tenant_scope_enabled_idx" ON "custom_instructions" USING btree ("tenant_id","scope_type","scope_id","enabled");--> statement-breakpoint
CREATE INDEX "custom_instr_tenant_mode_idx" ON "custom_instructions" USING btree ("tenant_id","mode");--> statement-breakpoint
CREATE UNIQUE INDEX "default_agent_instr_tenant_provider_uniq" ON "default_agent_instructions" USING btree ("tenant_id","provider");--> statement-breakpoint
CREATE INDEX "default_agent_instr_tenant_enabled_idx" ON "default_agent_instructions" USING btree ("tenant_id","enabled");--> statement-breakpoint
CREATE UNIQUE INDEX "default_agent_tools_tenant_provider_uniq" ON "default_agent_tools" USING btree ("tenant_id","provider");--> statement-breakpoint
CREATE INDEX "default_agent_tools_tenant_enabled_idx" ON "default_agent_tools" USING btree ("tenant_id","enabled");--> statement-breakpoint
CREATE UNIQUE INDEX "build_pipelines_tenant_project_name_uniq" ON "build_pipelines" USING btree ("tenant_id","project_id","name");--> statement-breakpoint
CREATE INDEX "build_pipelines_tenant_project_idx" ON "build_pipelines" USING btree ("tenant_id","project_id");--> statement-breakpoint
CREATE INDEX "build_pipelines_tenant_repo_idx" ON "build_pipelines" USING btree ("tenant_id","repository_id");--> statement-breakpoint
CREATE INDEX "build_pipelines_tenant_enabled_idx" ON "build_pipelines" USING btree ("tenant_id","enabled");--> statement-breakpoint
CREATE INDEX "build_pipelines_tenant_pipeline_repo_idx" ON "build_pipelines" USING btree ("tenant_id","pipeline_repository_id");--> statement-breakpoint
CREATE UNIQUE INDEX "deploy_steps_tenant_deploy_order_uniq" ON "deployment_steps" USING btree ("tenant_id","deployment_id","step_order");--> statement-breakpoint
CREATE INDEX "deploy_steps_tenant_deploy_order_idx" ON "deployment_steps" USING btree ("tenant_id","deployment_id","step_order");--> statement-breakpoint
CREATE UNIQUE INDEX "deploy_targets_tenant_project_name_uniq" ON "deployment_targets" USING btree ("tenant_id","project_id","name");--> statement-breakpoint
CREATE INDEX "deploy_targets_tenant_project_idx" ON "deployment_targets" USING btree ("tenant_id","project_id");--> statement-breakpoint
CREATE INDEX "deploy_targets_tenant_enabled_idx" ON "deployment_targets" USING btree ("tenant_id","enabled");--> statement-breakpoint
CREATE INDEX "deployments_tenant_project_created_idx" ON "deployments" USING btree ("tenant_id","project_id","created_at");--> statement-breakpoint
CREATE INDEX "deployments_tenant_target_status_idx" ON "deployments" USING btree ("tenant_id","deployment_target_id","status");--> statement-breakpoint
CREATE INDEX "pipeline_runs_tenant_pipeline_started_idx" ON "pipeline_runs" USING btree ("tenant_id","pipeline_id","started_at");--> statement-breakpoint
CREATE INDEX "pipeline_runs_tenant_status_idx" ON "pipeline_runs" USING btree ("tenant_id","status");--> statement-breakpoint
CREATE INDEX "api_keys_tenant_status_idx" ON "api_keys" USING btree ("tenant_id","status");--> statement-breakpoint
CREATE UNIQUE INDEX "api_keys_tenant_prefix_uniq" ON "api_keys" USING btree ("tenant_id","prefix");--> statement-breakpoint
CREATE UNIQUE INDEX "env_var_sets_tenant_scope_name_uniq" ON "env_var_sets" USING btree ("tenant_id","scope_type","scope_id","name");--> statement-breakpoint
CREATE INDEX "env_var_sets_tenant_scope_idx" ON "env_var_sets" USING btree ("tenant_id","scope_type","scope_id");--> statement-breakpoint
CREATE UNIQUE INDEX "env_vars_tenant_set_key_uniq" ON "env_vars" USING btree ("tenant_id","set_id","key");--> statement-breakpoint
CREATE INDEX "env_vars_tenant_set_idx" ON "env_vars" USING btree ("tenant_id","set_id");--> statement-breakpoint
-- Generated column for full-text trigram search on features
ALTER TABLE "features" ADD COLUMN "search_text" text GENERATED ALWAYS AS (coalesce(key,'') || ' ' || coalesce(name,'') || ' ' || coalesce(description,'')) STORED;--> statement-breakpoint
CREATE INDEX "features_search_text_trgm_idx" ON "features" USING gin ("search_text" gin_trgm_ops);--> statement-breakpoint
-- GIN trigram indexes for alias fuzzy search
CREATE INDEX "repo_aliases_alias_trgm_idx" ON "repository_aliases" USING gin ("alias" gin_trgm_ops);--> statement-breakpoint
CREATE INDEX "feat_aliases_alias_trgm_idx" ON "feature_aliases" USING gin ("alias" gin_trgm_ops);