CREATE TABLE "images" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "images_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"tenant_id" bigint NOT NULL,
	"agent_run_id" bigint,
	"ticket_id" bigint,
	"s3_key" text NOT NULL,
	"s3_bucket" text NOT NULL,
	"file_name" text NOT NULL,
	"mime_type" text NOT NULL,
	"size_bytes" integer NOT NULL,
	"purpose" text,
	"metadata_json" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "preview_deployments" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "preview_deployments_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"tenant_id" bigint NOT NULL,
	"agent_run_id" bigint,
	"repository_id" bigint NOT NULL,
	"branch" text NOT NULL,
	"feature_slug" text,
	"preview_url" text,
	"k8s_namespace" text,
	"k8s_deployment" text,
	"k8s_service" text,
	"k8s_ingress" text,
	"status" text DEFAULT 'pending' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"destroyed_at" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "agent_runs" ADD COLUMN "resolved_prompt" text;--> statement-breakpoint
ALTER TABLE "images" ADD CONSTRAINT "images_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "images" ADD CONSTRAINT "images_agent_run_id_agent_runs_id_fk" FOREIGN KEY ("agent_run_id") REFERENCES "public"."agent_runs"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "images" ADD CONSTRAINT "images_ticket_id_tickets_id_fk" FOREIGN KEY ("ticket_id") REFERENCES "public"."tickets"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "preview_deployments" ADD CONSTRAINT "preview_deployments_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "preview_deployments" ADD CONSTRAINT "preview_deployments_agent_run_id_agent_runs_id_fk" FOREIGN KEY ("agent_run_id") REFERENCES "public"."agent_runs"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "preview_deployments" ADD CONSTRAINT "preview_deployments_repository_id_repositories_id_fk" FOREIGN KEY ("repository_id") REFERENCES "public"."repositories"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "images_tenant_run_idx" ON "images" USING btree ("tenant_id","agent_run_id");--> statement-breakpoint
CREATE INDEX "images_tenant_ticket_idx" ON "images" USING btree ("tenant_id","ticket_id");--> statement-breakpoint
CREATE INDEX "images_tenant_created_idx" ON "images" USING btree ("tenant_id","created_at");--> statement-breakpoint
CREATE INDEX "preview_deploy_tenant_repo_branch_idx" ON "preview_deployments" USING btree ("tenant_id","repository_id","branch");--> statement-breakpoint
CREATE INDEX "preview_deploy_tenant_status_idx" ON "preview_deployments" USING btree ("tenant_id","status");--> statement-breakpoint
CREATE INDEX "preview_deploy_tenant_run_idx" ON "preview_deployments" USING btree ("tenant_id","agent_run_id");